# Generated by Django 4.2.1 on 2025-07-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='hi', max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
