# Generated by Django 5.1.4 on 2025-08-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
