# Generated by Django 5.1.4 on 2025-08-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_product_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='youtube_video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
