# Generated by Django 5.1.4 on 2025-09-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description for SEO (recommended max 160 characters).', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO.', max_length=255, null=True),
        ),
    ]
