# Generated by Django 5.1.4 on 2025-09-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_product_meta_description_product_meta_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_project',
            field=models.BooleanField(default=False, help_text="Check if this is a project; leave unchecked if it's a product."),
        ),
    ]
