# Generated by Django 6.0 on 2025-12-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_product_is_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for the main image.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for the gallery image.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for the variant image.', max_length=255, null=True),
        ),
    ]
