# Generated by Django 6.0 on 2026-02-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_product_alt_text_productimage_alt_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, help_text='e.g. https://www.facebook.com/IsolPaki', max_length=255, null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='e.g. https://www.instagram.com/yourpage', max_length=255, null=True)),
                ('youtube_url', models.URLField(blank=True, help_text='e.g. https://www.youtube.com/@Isol_pk', max_length=255, null=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='e.g. 923104505008 (Include country code without +)', max_length=20, null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='X/Twitter Profile URL', max_length=255, null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn Profile URL', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
