# Generated by Django 5.2.5 on 2026-07-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guarantee_text',
            field=models.CharField(blank=True, default='Pre-tested & Quality Checked before dispatch across Pakistan. 100% Genuine Guaranteed.', help_text='Custom buyer quality assurance callout.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='package_includes',
            field=models.TextField(blank=True, help_text='Items included in the box (one item per line, e.g. 1x ESP32 Board\n1x Pinout Guide).', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Select related products or accessories for cross-linking.', to='Store.product'),
        ),
    ]
