# Generated by Django 6.0 on 2026-08-20 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_product_guarantee_text_product_package_includes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Article Title')),
                ('slug', models.SlugField(help_text='Unique URL slug', max_length=280, unique=True)),
                ('category', models.CharField(choices=[('ai-ml', 'AI & Machine Learning'), ('iot-embedded', 'IoT & Embedded Systems'), ('robotics-hardware', 'Robotics & Hardware'), ('fyp-guides', 'Final Year Project (FYP) Guides'), ('tutorials', 'DIY Tutorials & How-To')], default='tutorials', max_length=50)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/images/')),
                ('excerpt', models.TextField(help_text='Short summary for article cards and meta description', max_length=500)),
                ('content', models.TextField(help_text='Full article content in HTML or Markdown')),
                ('author', models.CharField(default='ISOL Engineering Team', max_length=100)),
                ('reading_time', models.CharField(default='5 min read', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=300, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_products', models.ManyToManyField(blank=True, help_text='Products/kits mentioned in this tutorial for 1-click buying', related_name='blog_posts', to='Store.product')),
            ],
            options={
                'verbose_name': 'Blog & Tutorial Post',
                'verbose_name_plural': 'Blog & Tutorial Posts',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
