# Generated by Django 6.0 on 2026-08-21 16:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0020_blogpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Official Answer')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Approved questions are visible to all visitors')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_questions', to=settings.AUTH_USER_MODEL)),
                ('blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Store.blogpost')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Question',
                'verbose_name_plural': 'Community Questions',
                'ordering': ['-created_at'],
            },
        ),
    ]
